// Generated by CoffeeScript 1.10.0

/**
 * loader test 
 * @date 2016-03-11 10:43:29
 * @author Allenice <994298628@qq.com>
 * @link http://www.allenice233.com
 */
var Swig, addDependence, beautify_html, extend, inArray, path, utils;

path = require('path');

Swig = require('swig').Swig;

beautify_html = require('js-beautify').html;

utils = require('loader-utils');

module.exports = function(content) {
  var filename, filepath, isPartial, options, result, swig;
  this.cacheable();
  filepath = this.resourcePath;
  filename = path.basename(filepath);
  isPartial = /^_/.test(filename);
  this.query = utils.parseQuery(this.query);
  options = extend({}, {
    cache: false
  }, this.query);
  swig = new Swig(options);
  addDependence(swig, this);
  if (isPartial) {
    return '';
  }
  result = swig.renderFile(filepath, {
    name: 'Allenice'
  });
  return 'module.exports = ' + JSON.stringify(result) + ';';
};

addDependence = function(swig, loaderCtx) {
  var _load, swigLoader;
  swigLoader = extend({}, swig.options.loader);
  _load = swigLoader.load;
  swigLoader.load = function(filepath) {
    console.log(path.basename(filepath));
    if (filepath !== loaderCtx.resourcePath) {
      loaderCtx.addDependency(filepath);
    }
    return _load.apply(swigLoader, arguments);
  };
  return extend(swig.options, {
    loader: swigLoader
  });
};

extend = function(target) {
  var sources;
  sources = Array.prototype.slice.call(arguments, 1);
  sources.forEach(function(source) {
    return Object.keys(source || {}).forEach(function(key) {
      return target[key] = source[key];
    });
  });
  return target;
};

inArray = function(val, arr) {
  return (arr.filter(function(item) {
    return item === val;
  })).length > 0;
};
